name = "mongoose"
version = "0.3.0"
description = "HTTP server and client for Donna, backed by Mongoose"
authors = ["Nikolas Skyl <skylnikolas@gmail.com>"]
licences = ["MIT"]
repository = { type = "github", user = "NikolasSkyl", repo = "mongoose" }

[dependencies]
donna = { git = "https://github.com/donna-lang/donna_stdlib", version = ">=0.3.0 and <1.0.0" }

[dev-dependencies]
unittest = { git = "https://github.com/donna-lang/unittest", version = ">=0.2.0 and <1.0.0" }
